Updating README
signalfx/splunk-otel-java-lambda pull request #58
Opened 2021-09-01 17:21 UTC by apatterson-splunk

Updating readme to add the option to send spans directly to ingest. Slack conversation linked below:

https://splunk.slack.com/archives/CQ17ZQJFP/p1630355869051600

2021-09-01 17:26 UTC, mateuszrzeszutek commented on README.md
> +   You can also use the `jaeger-thrift-splunk' exporter to send spans directly to the Splunk Observability Cloud backend. You can update accomplish this by updating OTEL_EXPORTER_JAEGER_ENDPOINT to t
```suggestion
   You can also use the `jaeger-thrift-splunk` exporter to send spans directly to the Splunk Observability Cloud backend. You can update accomplish this by updating `OTEL_EXPORTER_JAEGER_ENDPOINT` to the ingest URL.
```

2021-09-01 17:27 UTC, mateuszrzeszutek commented
CC @theletterf

2021-09-02 07:58 UTC, theletterf requested changes

2021-09-02 07:58 UTC, theletterf commented on README.md
> +   You can also use the `jaeger-thrift-splunk' exporter to send spans directly to the Splunk Observability Cloud backend. You can update accomplish this by updating OTEL_EXPORTER_JAEGER_ENDPOINT to t
```suggestion
   You can also use the `jaeger-thrift-splunk` exporter to send spans directly to the Splunk Observability Cloud backend. You can accomplish this by pointing `OTEL_EXPORTER_JAEGER_ENDPOINT` to the ingest URL.
```

2021-09-03 09:38 UTC, kubawach commented
@mateuszrzeszutek @apatterson-splunk per splunk's doc (https://docs.signalfx.com/en/latest/apm/apm-getting-started/apm-supported-span-formats.html#apm-ingest-endpoint-compatible-span-formats) both jaeger-thrift and otlp are supported on the ingest, so I think the doc change should say that the user can select either exporter but has to set token and endpoint. WDYT?

2021-09-06 07:45 UTC, mateuszrzeszutek commented
Ingest only supports HTTP+protobuf OTLP -- I'm not sure that the SDK supports that mode though, we should test that before we mention it in the docs.

2021-09-16 09:10 UTC, kubawach approved these changes

2021-09-28 10:07 UTC, merged